version: 0.2
phases:
    build:
      commands:
      - echo building
      - sudo gradle wrapper --gradle-version 6.8.3
      - chmod +x ./gradlew
      - ./gradlew build
artifacts:
    files:
    - build/libs/EducaApp-0.0.1-SNAPSHOT.war
    discard-paths: yes