version: 0.2
phases:
    build:
      commands:
      - echo building
      - gradle wrapper --gradle-version 6.8.3
      - chmod +x ./gradlew
      - ./gradlew build
artifacts:
    files:
    - build/libs/Educapp.jar
    discard-paths: yes